name: Algorithms In Scala - CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.11
      - name: Run tests
        run: sbt test
